//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DevMsgForm.BITFIDEV {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DEVTOOLSoap", Namespace="https://bitfi.com/dataservices/")]
    public partial class DEVTOOL : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetNoxMessagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSupportArticleByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSupportTagListOperationCompleted;
        
        private System.Threading.SendOrPostCallback POST_AddSuppotArticleOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConvertFromRIPEMD_ToBase58OperationCompleted;
        
        private System.Threading.SendOrPostCallback ConvertFromBase58_ToRIPEMDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SignMessageTestTool_Base58KeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback SignMessageTestTool_HexKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback POST_AddDownloadOperationCompleted;
        
        private System.Threading.SendOrPostCallback POST_ChangeDisplayStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback POST_AddArticleTestToolOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBTCUSDRateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DEVTOOL() {
       
      this.Url = "https://bitfi.dev/NoxMessages/V2/DEVTOOL.ASMX";
      if ((this.IsLocalFileSystemWebService(this.Url) == true))
      {
        this.UseDefaultCredentials = true;
        this.useDefaultCredentialsSetExplicitly = false;
      }
      else
      {
        this.useDefaultCredentialsSetExplicitly = true;
      }
    }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNoxMessagesCompletedEventHandler GetNoxMessagesCompleted;
        
        /// <remarks/>
        public event GetSupportArticleByIDCompletedEventHandler GetSupportArticleByIDCompleted;
        
        /// <remarks/>
        public event GetSupportTagListCompletedEventHandler GetSupportTagListCompleted;
        
        /// <remarks/>
        public event POST_AddSuppotArticleCompletedEventHandler POST_AddSuppotArticleCompleted;
        
        /// <remarks/>
        public event AddProfileCompletedEventHandler AddProfileCompleted;
        
        /// <remarks/>
        public event ConvertFromRIPEMD_ToBase58CompletedEventHandler ConvertFromRIPEMD_ToBase58Completed;
        
        /// <remarks/>
        public event ConvertFromBase58_ToRIPEMDCompletedEventHandler ConvertFromBase58_ToRIPEMDCompleted;
        
        /// <remarks/>
        public event SignMessageTestTool_Base58KeyCompletedEventHandler SignMessageTestTool_Base58KeyCompleted;
        
        /// <remarks/>
        public event SignMessageTestTool_HexKeyCompletedEventHandler SignMessageTestTool_HexKeyCompleted;
        
        /// <remarks/>
        public event POST_AddDownloadCompletedEventHandler POST_AddDownloadCompleted;
        
        /// <remarks/>
        public event POST_ChangeDisplayStatusCompletedEventHandler POST_ChangeDisplayStatusCompleted;
        
        /// <remarks/>
        public event POST_AddArticleTestToolCompletedEventHandler POST_AddArticleTestToolCompleted;
        
        /// <remarks/>
        public event GetBTCUSDRateCompletedEventHandler GetBTCUSDRateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://bitfi.com/dataservices/GetNoxMessages", RequestNamespace="https://bitfi.com/dataservices/", ResponseNamespace="https://bitfi.com/dataservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NoxMessagesBasic[] GetNoxMessages() {
            object[] results = this.Invoke("GetNoxMessages", new object[0]);
            return ((NoxMessagesBasic[])(results[0]));
        }
        
        /// <remarks/>
        public void GetNoxMessagesAsync() {
            this.GetNoxMessagesAsync(null);
        }
        
        /// <remarks/>
        public void GetNoxMessagesAsync(object userState) {
            if ((this.GetNoxMessagesOperationCompleted == null)) {
                this.GetNoxMessagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNoxMessagesOperationCompleted);
            }
            this.InvokeAsync("GetNoxMessages", new object[0], this.GetNoxMessagesOperationCompleted, userState);
        }
        
        private void OnGetNoxMessagesOperationCompleted(object arg) {
            if ((this.GetNoxMessagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNoxMessagesCompleted(this, new GetNoxMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://bitfi.com/dataservices/GetSupportArticleByID", RequestNamespace="https://bitfi.com/dataservices/", ResponseNamespace="https://bitfi.com/dataservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SupportArticle GetSupportArticleByID(string LineID) {
            object[] results = this.Invoke("GetSupportArticleByID", new object[] {
                        LineID});
            return ((SupportArticle)(results[0]));
        }
        
        /// <remarks/>
        public void GetSupportArticleByIDAsync(string LineID) {
            this.GetSupportArticleByIDAsync(LineID, null);
        }
        
        /// <remarks/>
        public void GetSupportArticleByIDAsync(string LineID, object userState) {
            if ((this.GetSupportArticleByIDOperationCompleted == null)) {
                this.GetSupportArticleByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSupportArticleByIDOperationCompleted);
            }
            this.InvokeAsync("GetSupportArticleByID", new object[] {
                        LineID}, this.GetSupportArticleByIDOperationCompleted, userState);
        }
        
        private void OnGetSupportArticleByIDOperationCompleted(object arg) {
            if ((this.GetSupportArticleByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSupportArticleByIDCompleted(this, new GetSupportArticleByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://bitfi.com/dataservices/GetSupportTagList", RequestNamespace="https://bitfi.com/dataservices/", ResponseNamespace="https://bitfi.com/dataservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public NoxMessagesBasic[] GetSupportTagList() {
            object[] results = this.Invoke("GetSupportTagList", new object[0]);
            return ((NoxMessagesBasic[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSupportTagListAsync() {
            this.GetSupportTagListAsync(null);
        }
        
        /// <remarks/>
        public void GetSupportTagListAsync(object userState) {
            if ((this.GetSupportTagListOperationCompleted == null)) {
                this.GetSupportTagListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSupportTagListOperationCompleted);
            }
            this.InvokeAsync("GetSupportTagList", new object[0], this.GetSupportTagListOperationCompleted, userState);
        }
        
        private void OnGetSupportTagListOperationCompleted(object arg) {
            if ((this.GetSupportTagListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSupportTagListCompleted(this, new GetSupportTagListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://bitfi.com/dataservices/POST_AddSuppotArticle", RequestNamespace="https://bitfi.com/dataservices/", ResponseNamespace="https://bitfi.com/dataservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TxnResponse POST_AddSuppotArticle(string HexKey, string ArticleTitle, string ArticleSubTitle, string ArticleDescription, string ArticleTag, string ArticleContent_Base64) {
            object[] results = this.Invoke("POST_AddSuppotArticle", new object[] {
                        HexKey,
                        ArticleTitle,
                        ArticleSubTitle,
                        ArticleDescription,
                        ArticleTag,
                        ArticleContent_Base64});
            return ((TxnResponse)(results[0]));
        }
        
        /// <remarks/>
        public void POST_AddSuppotArticleAsync(string HexKey, string ArticleTitle, string ArticleSubTitle, string ArticleDescription, string ArticleTag, string ArticleContent_Base64) {
            this.POST_AddSuppotArticleAsync(HexKey, ArticleTitle, ArticleSubTitle, ArticleDescription, ArticleTag, ArticleContent_Base64, null);
        }
        
        /// <remarks/>
        public void POST_AddSuppotArticleAsync(string HexKey, string ArticleTitle, string ArticleSubTitle, string ArticleDescription, string ArticleTag, string ArticleContent_Base64, object userState) {
            if ((this.POST_AddSuppotArticleOperationCompleted == null)) {
                this.POST_AddSuppotArticleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPOST_AddSuppotArticleOperationCompleted);
            }
            this.InvokeAsync("POST_AddSuppotArticle", new object[] {
                        HexKey,
                        ArticleTitle,
                        ArticleSubTitle,
                        ArticleDescription,
                        ArticleTag,
                        ArticleContent_Base64}, this.POST_AddSuppotArticleOperationCompleted, userState);
        }
        
        private void OnPOST_AddSuppotArticleOperationCompleted(object arg) {
            if ((this.POST_AddSuppotArticleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.POST_AddSuppotArticleCompleted(this, new POST_AddSuppotArticleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://bitfi.com/dataservices/AddProfile", RequestNamespace="https://bitfi.com/dataservices/", ResponseNamespace="https://bitfi.com/dataservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddProfile(string PubKey_RIPEMD, string ProfileName, int ProfileType, string ProfileURL, string AdminSignatureOfPubKeyMsg) {
            object[] results = this.Invoke("AddProfile", new object[] {
                        PubKey_RIPEMD,
                        ProfileName,
                        ProfileType,
                        ProfileURL,
                        AdminSignatureOfPubKeyMsg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddProfileAsync(string PubKey_RIPEMD, string ProfileName, int ProfileType, string ProfileURL, string AdminSignatureOfPubKeyMsg) {
            this.AddProfileAsync(PubKey_RIPEMD, ProfileName, ProfileType, ProfileURL, AdminSignatureOfPubKeyMsg, null);
        }
        
        /// <remarks/>
        public void AddProfileAsync(string PubKey_RIPEMD, string ProfileName, int ProfileType, string ProfileURL, string AdminSignatureOfPubKeyMsg, object userState) {
            if ((this.AddProfileOperationCompleted == null)) {
                this.AddProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddProfileOperationCompleted);
            }
            this.InvokeAsync("AddProfile", new object[] {
                        PubKey_RIPEMD,
                        ProfileName,
                        ProfileType,
                        ProfileURL,
                        AdminSignatureOfPubKeyMsg}, this.AddProfileOperationCompleted, userState);
        }
        
        private void OnAddProfileOperationCompleted(object arg) {
            if ((this.AddProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddProfileCompleted(this, new AddProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://bitfi.com/dataservices/ConvertFromRIPEMD_ToBase58", RequestNamespace="https://bitfi.com/dataservices/", ResponseNamespace="https://bitfi.com/dataservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConvertFromRIPEMD_ToBase58(string PubKey) {
            object[] results = this.Invoke("ConvertFromRIPEMD_ToBase58", new object[] {
                        PubKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConvertFromRIPEMD_ToBase58Async(string PubKey) {
            this.ConvertFromRIPEMD_ToBase58Async(PubKey, null);
        }
        
        /// <remarks/>
        public void ConvertFromRIPEMD_ToBase58Async(string PubKey, object userState) {
            if ((this.ConvertFromRIPEMD_ToBase58OperationCompleted == null)) {
                this.ConvertFromRIPEMD_ToBase58OperationCompleted = new System.Threading.SendOrPostCallback(this.OnConvertFromRIPEMD_ToBase58OperationCompleted);
            }
            this.InvokeAsync("ConvertFromRIPEMD_ToBase58", new object[] {
                        PubKey}, this.ConvertFromRIPEMD_ToBase58OperationCompleted, userState);
        }
        
        private void OnConvertFromRIPEMD_ToBase58OperationCompleted(object arg) {
            if ((this.ConvertFromRIPEMD_ToBase58Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConvertFromRIPEMD_ToBase58Completed(this, new ConvertFromRIPEMD_ToBase58CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://bitfi.com/dataservices/ConvertFromBase58_ToRIPEMD", RequestNamespace="https://bitfi.com/dataservices/", ResponseNamespace="https://bitfi.com/dataservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConvertFromBase58_ToRIPEMD(string PubKey) {
            object[] results = this.Invoke("ConvertFromBase58_ToRIPEMD", new object[] {
                        PubKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConvertFromBase58_ToRIPEMDAsync(string PubKey) {
            this.ConvertFromBase58_ToRIPEMDAsync(PubKey, null);
        }
        
        /// <remarks/>
        public void ConvertFromBase58_ToRIPEMDAsync(string PubKey, object userState) {
            if ((this.ConvertFromBase58_ToRIPEMDOperationCompleted == null)) {
                this.ConvertFromBase58_ToRIPEMDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConvertFromBase58_ToRIPEMDOperationCompleted);
            }
            this.InvokeAsync("ConvertFromBase58_ToRIPEMD", new object[] {
                        PubKey}, this.ConvertFromBase58_ToRIPEMDOperationCompleted, userState);
        }
        
        private void OnConvertFromBase58_ToRIPEMDOperationCompleted(object arg) {
            if ((this.ConvertFromBase58_ToRIPEMDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConvertFromBase58_ToRIPEMDCompleted(this, new ConvertFromBase58_ToRIPEMDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://bitfi.com/dataservices/SignMessageTestTool_Base58Key", RequestNamespace="https://bitfi.com/dataservices/", ResponseNamespace="https://bitfi.com/dataservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SignMessageTestTool_Base58Key(string Base58Key, string Msg) {
            object[] results = this.Invoke("SignMessageTestTool_Base58Key", new object[] {
                        Base58Key,
                        Msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SignMessageTestTool_Base58KeyAsync(string Base58Key, string Msg) {
            this.SignMessageTestTool_Base58KeyAsync(Base58Key, Msg, null);
        }
        
        /// <remarks/>
        public void SignMessageTestTool_Base58KeyAsync(string Base58Key, string Msg, object userState) {
            if ((this.SignMessageTestTool_Base58KeyOperationCompleted == null)) {
                this.SignMessageTestTool_Base58KeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignMessageTestTool_Base58KeyOperationCompleted);
            }
            this.InvokeAsync("SignMessageTestTool_Base58Key", new object[] {
                        Base58Key,
                        Msg}, this.SignMessageTestTool_Base58KeyOperationCompleted, userState);
        }
        
        private void OnSignMessageTestTool_Base58KeyOperationCompleted(object arg) {
            if ((this.SignMessageTestTool_Base58KeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignMessageTestTool_Base58KeyCompleted(this, new SignMessageTestTool_Base58KeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://bitfi.com/dataservices/SignMessageTestTool_HexKey", RequestNamespace="https://bitfi.com/dataservices/", ResponseNamespace="https://bitfi.com/dataservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SignMessageTestTool_HexKey(string HexKey, string Msg) {
            object[] results = this.Invoke("SignMessageTestTool_HexKey", new object[] {
                        HexKey,
                        Msg});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SignMessageTestTool_HexKeyAsync(string HexKey, string Msg) {
            this.SignMessageTestTool_HexKeyAsync(HexKey, Msg, null);
        }
        
        /// <remarks/>
        public void SignMessageTestTool_HexKeyAsync(string HexKey, string Msg, object userState) {
            if ((this.SignMessageTestTool_HexKeyOperationCompleted == null)) {
                this.SignMessageTestTool_HexKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignMessageTestTool_HexKeyOperationCompleted);
            }
            this.InvokeAsync("SignMessageTestTool_HexKey", new object[] {
                        HexKey,
                        Msg}, this.SignMessageTestTool_HexKeyOperationCompleted, userState);
        }
        
        private void OnSignMessageTestTool_HexKeyOperationCompleted(object arg) {
            if ((this.SignMessageTestTool_HexKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignMessageTestTool_HexKeyCompleted(this, new SignMessageTestTool_HexKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://bitfi.com/dataservices/POST_AddDownload", RequestNamespace="https://bitfi.com/dataservices/", ResponseNamespace="https://bitfi.com/dataservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TxnResponse POST_AddDownload(string HexKey, string Tag, string Description, string DownloadURL) {
            object[] results = this.Invoke("POST_AddDownload", new object[] {
                        HexKey,
                        Tag,
                        Description,
                        DownloadURL});
            return ((TxnResponse)(results[0]));
        }
        
        /// <remarks/>
        public void POST_AddDownloadAsync(string HexKey, string Tag, string Description, string DownloadURL) {
            this.POST_AddDownloadAsync(HexKey, Tag, Description, DownloadURL, null);
        }
        
        /// <remarks/>
        public void POST_AddDownloadAsync(string HexKey, string Tag, string Description, string DownloadURL, object userState) {
            if ((this.POST_AddDownloadOperationCompleted == null)) {
                this.POST_AddDownloadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPOST_AddDownloadOperationCompleted);
            }
            this.InvokeAsync("POST_AddDownload", new object[] {
                        HexKey,
                        Tag,
                        Description,
                        DownloadURL}, this.POST_AddDownloadOperationCompleted, userState);
        }
        
        private void OnPOST_AddDownloadOperationCompleted(object arg) {
            if ((this.POST_AddDownloadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.POST_AddDownloadCompleted(this, new POST_AddDownloadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://bitfi.com/dataservices/POST_ChangeDisplayStatus", RequestNamespace="https://bitfi.com/dataservices/", ResponseNamespace="https://bitfi.com/dataservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TxnResponse POST_ChangeDisplayStatus(string HexKey, string TxnID, bool DisplayInList) {
            object[] results = this.Invoke("POST_ChangeDisplayStatus", new object[] {
                        HexKey,
                        TxnID,
                        DisplayInList});
            return ((TxnResponse)(results[0]));
        }
        
        /// <remarks/>
        public void POST_ChangeDisplayStatusAsync(string HexKey, string TxnID, bool DisplayInList) {
            this.POST_ChangeDisplayStatusAsync(HexKey, TxnID, DisplayInList, null);
        }
        
        /// <remarks/>
        public void POST_ChangeDisplayStatusAsync(string HexKey, string TxnID, bool DisplayInList, object userState) {
            if ((this.POST_ChangeDisplayStatusOperationCompleted == null)) {
                this.POST_ChangeDisplayStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPOST_ChangeDisplayStatusOperationCompleted);
            }
            this.InvokeAsync("POST_ChangeDisplayStatus", new object[] {
                        HexKey,
                        TxnID,
                        DisplayInList}, this.POST_ChangeDisplayStatusOperationCompleted, userState);
        }
        
        private void OnPOST_ChangeDisplayStatusOperationCompleted(object arg) {
            if ((this.POST_ChangeDisplayStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.POST_ChangeDisplayStatusCompleted(this, new POST_ChangeDisplayStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://bitfi.com/dataservices/POST_AddArticleTestTool", RequestNamespace="https://bitfi.com/dataservices/", ResponseNamespace="https://bitfi.com/dataservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TxnResponse POST_AddArticleTestTool(string HexKey, string Category, string ArticleTitle, string ArticleSubTitle, string ArticleDescription, string ArticleTag, string ArticleContent_Base64) {
            object[] results = this.Invoke("POST_AddArticleTestTool", new object[] {
                        HexKey,
                        Category,
                        ArticleTitle,
                        ArticleSubTitle,
                        ArticleDescription,
                        ArticleTag,
                        ArticleContent_Base64});
            return ((TxnResponse)(results[0]));
        }
        
        /// <remarks/>
        public void POST_AddArticleTestToolAsync(string HexKey, string Category, string ArticleTitle, string ArticleSubTitle, string ArticleDescription, string ArticleTag, string ArticleContent_Base64) {
            this.POST_AddArticleTestToolAsync(HexKey, Category, ArticleTitle, ArticleSubTitle, ArticleDescription, ArticleTag, ArticleContent_Base64, null);
        }
        
        /// <remarks/>
        public void POST_AddArticleTestToolAsync(string HexKey, string Category, string ArticleTitle, string ArticleSubTitle, string ArticleDescription, string ArticleTag, string ArticleContent_Base64, object userState) {
            if ((this.POST_AddArticleTestToolOperationCompleted == null)) {
                this.POST_AddArticleTestToolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPOST_AddArticleTestToolOperationCompleted);
            }
            this.InvokeAsync("POST_AddArticleTestTool", new object[] {
                        HexKey,
                        Category,
                        ArticleTitle,
                        ArticleSubTitle,
                        ArticleDescription,
                        ArticleTag,
                        ArticleContent_Base64}, this.POST_AddArticleTestToolOperationCompleted, userState);
        }
        
        private void OnPOST_AddArticleTestToolOperationCompleted(object arg) {
            if ((this.POST_AddArticleTestToolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.POST_AddArticleTestToolCompleted(this, new POST_AddArticleTestToolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://bitfi.com/dataservices/GetBTCUSDRate", RequestNamespace="https://bitfi.com/dataservices/", ResponseNamespace="https://bitfi.com/dataservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBTCUSDRate(bool round) {
            object[] results = this.Invoke("GetBTCUSDRate", new object[] {
                        round});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBTCUSDRateAsync(bool round) {
            this.GetBTCUSDRateAsync(round, null);
        }
        
        /// <remarks/>
        public void GetBTCUSDRateAsync(bool round, object userState) {
            if ((this.GetBTCUSDRateOperationCompleted == null)) {
                this.GetBTCUSDRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBTCUSDRateOperationCompleted);
            }
            this.InvokeAsync("GetBTCUSDRate", new object[] {
                        round}, this.GetBTCUSDRateOperationCompleted, userState);
        }
        
        private void OnGetBTCUSDRateOperationCompleted(object arg) {
            if ((this.GetBTCUSDRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBTCUSDRateCompleted(this, new GetBTCUSDRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://bitfi.com/dataservices/")]
    public partial class NoxMessagesBasic {
        
        private string mobMessageField;
        
        private System.Guid idField;
        
        private long lineIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MobMessage {
            get {
                return this.mobMessageField;
            }
            set {
                this.mobMessageField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public long LineID {
            get {
                return this.lineIDField;
            }
            set {
                this.lineIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://bitfi.com/dataservices/")]
    public partial class TxnResponse {
        
        private bool successField;
        
        private string error_messageField;
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string error_message {
            get {
                return this.error_messageField;
            }
            set {
                this.error_messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://bitfi.com/dataservices/")]
    public partial class SupportArticle {
        
        private string messageField;
        
        private string signatureField;
        
        private string titleField;
        
        private string tagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetNoxMessagesCompletedEventHandler(object sender, GetNoxMessagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNoxMessagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNoxMessagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NoxMessagesBasic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NoxMessagesBasic[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetSupportArticleByIDCompletedEventHandler(object sender, GetSupportArticleByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSupportArticleByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSupportArticleByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SupportArticle Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SupportArticle)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetSupportTagListCompletedEventHandler(object sender, GetSupportTagListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSupportTagListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSupportTagListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public NoxMessagesBasic[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((NoxMessagesBasic[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void POST_AddSuppotArticleCompletedEventHandler(object sender, POST_AddSuppotArticleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class POST_AddSuppotArticleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal POST_AddSuppotArticleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TxnResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TxnResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void AddProfileCompletedEventHandler(object sender, AddProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ConvertFromRIPEMD_ToBase58CompletedEventHandler(object sender, ConvertFromRIPEMD_ToBase58CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConvertFromRIPEMD_ToBase58CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConvertFromRIPEMD_ToBase58CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ConvertFromBase58_ToRIPEMDCompletedEventHandler(object sender, ConvertFromBase58_ToRIPEMDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConvertFromBase58_ToRIPEMDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConvertFromBase58_ToRIPEMDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SignMessageTestTool_Base58KeyCompletedEventHandler(object sender, SignMessageTestTool_Base58KeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignMessageTestTool_Base58KeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignMessageTestTool_Base58KeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SignMessageTestTool_HexKeyCompletedEventHandler(object sender, SignMessageTestTool_HexKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignMessageTestTool_HexKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignMessageTestTool_HexKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void POST_AddDownloadCompletedEventHandler(object sender, POST_AddDownloadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class POST_AddDownloadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal POST_AddDownloadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TxnResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TxnResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void POST_ChangeDisplayStatusCompletedEventHandler(object sender, POST_ChangeDisplayStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class POST_ChangeDisplayStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal POST_ChangeDisplayStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TxnResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TxnResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void POST_AddArticleTestToolCompletedEventHandler(object sender, POST_AddArticleTestToolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class POST_AddArticleTestToolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal POST_AddArticleTestToolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TxnResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TxnResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetBTCUSDRateCompletedEventHandler(object sender, GetBTCUSDRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBTCUSDRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBTCUSDRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591